name: build-test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.3.0
    - uses: actions/setup-node@v5.0.0
      with:
         node-version: '16.20.2'
    - name: use yarn
      run: |
       yarn install
       yarn action
